spring.datasource.url=jdbc:postgresql://dpg-d8gr5k6rnols73evuplg-a.oregon-postgres.render.com:5432/gamestudio_mxcg?sslmode=require
spring.datasource.username=gamestudio_user
spring.datasource.password=fgmyMCEljekLb8LQtEHhuvCn11M7pnS4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximumPoolSize=2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
