spring.datasource.url=jdbc:postgresql://dpg-d7t3bgnavr4c73fftg6g-a:5432/gamestudio_ztw3?sslmode=require
spring.datasource.username=gamestudio_ztw3_user
spring.datasource.password=NyTQgOj2uKb8x6NglkhzHcDUfphZE1VA
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximumPoolSize=2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}
