spring.datasource.url=jdbc:postgresql://localhost/gamestudio
spring.datasource.username=postgres
spring.datasource.password=chlpaty.tamara
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximumPoolSize=2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=false
server.servlet.session.cookie.name=SLITHERLINK_SESSION
server.servlet.session.cookie.same-site=strict